### ISSUE TITLE
InlineVarPlugin seems to ignore @var annotations

### ISSUE THREAD

**Issue by Aerendir** [Drenso/PhanExtensions#10]
```php
use App\Entity\User;

...

        /** @var User $user */
        $user = $event->getUser();

        ...

        $data['data'] = [
            '@id'      => '/api/users/' . $user->getId(),
        ...
```

This code produces this error:

> PhanUndeclaredMethod Call to undeclared method \Symfony\Component\Security\Core\User\UserInterface::getId

The interface actually doesn't have the `getId()` method, but my concrete implementation has it (it is a `User` entity that extends the `User` entity from FOSUserBundle).

**Comment by bobvandevijver** [comment]
It might not be completely clear from the documentation, but this case is actually not what the `InlineVarPlugin` is meant to solve. It is meant to register the type `User` as being used somewhere in your file, so that you won't get a `PhanUnreferencedUseNormal` error if it's the only place where it's referenced in the file. It also generates an error when you try to use an unknown type in your annotation. 

The `MethodPlugin` and the `ThrowsPlugin` (although the latter shouldn't be needed anymore) have the same behaviour, but work for the `@method` and `@throws` statements.

If you want to override the type of the variable returned by the `getUser()` call, I can recommend using the following code as replacement for your middle part:
```php
$user = $event->getUser();
assert($user instanceof User);
```

This wont give any performance impact (or even "crash") as long as you make sure that [`zend.assertions`](https://www.php.net/manual/en/function.assert.php) is set to `-1` (which is usually the default value).
