### ISSUE TITLE
@method Annotation not working with Phan 3.2.0 Update 

### ISSUE THREAD

**Issue by Robsangar** [Drenso/PhanExtensions#16]
By updating Phan to 3.2.0 I am getting errors with the @method Annotation used in PHPDoc by doctrine. 

`PhanParamSignaturePHPDocMismatchHasNoParamType Declaration of real/@method function find($id, $lockMode = null, $lockVersion = null) should be compatible with real/@method function find($id, $lockMode = null, $lockVersion = null) (parameter #2 with no type cannot replace original parameter with type 'int|null') defined in vendor/doctrine/orm/lib/Doctrine/ORM\EntityRepository.php:149`

Its it causes by drenso extension not being compatible with the new phan version?

**Comment by bobvandevijver** [comment]
I'm pretty sure this isn't caused by our extensions. The error type is `PhanParamSignaturePHPDocMismatchHasNoParamType` is a native Phan error type not related to anything we touch.  It seems to indicate that you have some mismatch between the typing of the implementation and your docblock. Anyways, it is hard to say anything useful without the actual source triggering this ;)
