### ISSUE TITLE
The parser is not able to read ORM annotations with backslash 

### ISSUE THREAD

**Issue by eliaspn** [Drenso/PhanExtensions#4]
I have the entities generated by Simfony with the help of `php bin/console make:entity`

phan throws the following:
`src/Entity/Campaigns.php:12 AnnotationNotImported The classlike \Doctrine\ORM\Mapping\index annotation is undeclared (generated by DrensoAnnotation plugin)
`

the code block looks like this:
```
<?php

namespace App\Entity;
use Doctrine\ORM\Mapping as ORM;

/**
 * Campaigns
 *
 * @ORM/Table(name="campaigns", indexes={@ORM\Index(name="supplier_fk", columns={"supplier_fk"}), @ORM\Index(name="initiator", columns={"initiator"})})
 * @ORM\Entity
 */
class Campaigns extends BaseEntity
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="bigint", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;
```

Notice for `@ORM/Table` I've changed the backslash with forward and it works.

**Comment by bobvandevijver** [comment]
I'm not sure what's exactly going wrong here: the plugin should function correctly with these blocks. For example, I use the following and it works fine:

```
@ORM\Table(name="association", indexes={@ORM\Index(columns={"id"})})
```

Make sure that all annotations are correct (use the backwards slashes), and also make sure you're using the latest version of this plugin. If this still not works, can you post a full workspace (including Phan configuration etc) so I can experiment with it?

**Comment by OwnerOfThisIsle** [comment]
I first thought, that I had a similar issue, but than I realised that in my case the error

`src\Entity\Item.php:10 AnnotationNotImported The classlike \Doctrine\ORM\Mapping\entity annotation is undeclared (generated by DrensoAnnotation plugin)`

appeared, because my .phan\config does not include `vendor `in the directory list for performance reasons, so I had to add `vendor\doctrine\orm\lib\Doctrine\ORM\Mapping` to that list.
(Just like any other class from my vendor directory that is actually used.)

Maybe this even would solve the original post from eliaspn, I also experienced that some of the error  messages disappear (strangely) when I change backslash with forward.

**Comment by bobvandevijver** [comment]
That would make sense: the classes must be declared/available for Phan in order to be recognised correctly. I normally have the `vendor` directory in the mentioned `directory_list`, but it is also excluded from analysis in `exclude_analysis_directory_list`.

@eliaspn Did you manage to solve your problem, or maybe the solution of @OwnerOfThisIsle helps in you case?

**Comment by bobvandevijver** [comment]
Closing this due to no response for a long time.
